<html>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<head>
<title>Section 6.13.&nbsp; try Blocks and Exception Handling</title>
<link rel="STYLESHEET" type="text/css" href="images/style.css">
<link rel="STYLESHEET" type="text/css" href="images/docsafari.css">
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td><div STYLE="MARGIN-LEFT: 0.15in;"><a href="toc.html"><img src="images/teamlib.gif" width="62" height="15" border="0" align="absmiddle"  alt="Team LiB"></a></div></td>
<td align="right"><div STYLE="MARGIN-LEFT: 0.15in;">
<a href=ch06lev1sec12.html><img src="images/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
<a href=ch06lev1sec14.html><img src="images/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</div></td></tr></table>
<br><table width="100%" border="0" cellspacing="0" cellpadding="0"><tr><td valign="top"><a name="ch06lev1sec13"></a>
<h3 class="docSection1Title">6.13. <tt>try</tt> Blocks and Exception Handling</H3>
<p class="docText">Handling errors and other anomalous behavior in programs can be one of the most difficult parts of designing any system. Long-lived, interactive systems such as communication switches and routers can devote as much as 90 percent of their code to error detection and error handling. With the proliferation of Web-based applications that run indefinitely, attention to error handling is becoming more important to more and more programmers.</P>
<p class="docText"><a name="idd1e45495"></a><a name="idd1e45501"></a><a name="idd1e45506"></a><a name="idd1e45511"></a><a name="idd1e45517"></a><a name="idd1e45526"></a><a name="idd1e45533"></a><a name="idd1e45538"></a><a name="idd1e45542"></a><a name="idd1e45546"></a>Exceptions are run-time anomalies, such as running out of memory or encountering unexpected input. Exceptions exist outside the normal functioning of the program and require immediate handling by the program.</p>
<p class="docText">In well-designed systems, exceptions represent a subset of the program's error handling. Exceptions are most useful when the code that detects a problem cannot handle it. In such cases, the part of the program that detects the problem needs a way to transfer control to the part of the program that can handle the problem. The error-detecting part also needs to be able to indicate what kind of problem occurred and may want to provide additional information.</P>
<p class="docText">Exceptions support this kind of communication between the error-detecting and error-handling parts of a program. In C++ exception handling involves:</p>
<div style="font-weight:bold"><ol class="docList" type="1"><li><div style="font-weight:normal"><p class="docList"><B><a name="ch06term25"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_25"><span class="docEmphStrong"><tt>tHRow</tt> expressions</span></a></b>, which the error-detecting part uses to indicate that it encountered an error that it cannot handle. We say that a <tt>throw</tt> <b><a name="ch06term22"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_22">raises</a></b> an exceptional condition.</p></div></li><li><div style="font-weight:normal"><p class="docList"><B><a name="ch06term26"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_26"><span class="docEmphStrong"><tt>try</tt> blocks</span></a></b>, which the error-handling part uses to deal with an exception. A <tt>TRy</tt> block starts with keyword <tt>TRy</tt> and ends with one or more <b><a name="ch06term5"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_05"><span class="docEmphStrong"><tt>catch</tt> clauses</span></a></b>. Exceptions thrown from code executed inside a <tt>try</tt> block are usually handled by one of the <tt>catch</tt> clauses. Because they &quot;handle&quot; the exception, catch clauses are known as <b><a name="ch06term12"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_12">handlers</a></b>.</P></div></LI><li><div style="font-weight:normal"><p class="docList">A set of <b><a name="ch06term11"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_11"><span class="docEmphStrong"><tt>exception</tt> classes</span></a></b> defined by the library, which are used to pass the information about an error between a <tt>throw</tt> and an associated <tt>catch</tt>.</p></div></LI></ol></div>
<p class="docText">In the remainder of this section we'll introduce these three components of exception handling. We'll have more to say about exceptions in <a class="docLink" href="ch17lev1sec1.html#ch17lev1sec1">Section 17.1</a> (p. <a class="docLink" href="ch17lev1sec1.html#ch17lev1sec1">688</a>).</p>
<a name="ch06lev2sec13"></a>
<h4 class="docSection2Title">6.13.1. A <tt>tHRow</tt> Expression</h4>
<p class="docText">An exception is thrown using a <tt>throw</tt> expression, which consists of the keyword <tt>tHRow</tt> followed by an expression. A <tt>throw</tt> expression is usually followed by a semicolon, making it into an expression statement. The type of the expression determines what kind of exception is thrown.</P>
<p class="docText">As a simple example, recall the program on page <a class="docLink" href="ch01lev1sec5.html#ch01sb13">24</a> that added two objects of type <tt>Sales_item</tt>. That program checked whether the records it read referred to the same book. If not, it printed a message and exited.</p>
<pre>
     Sales_item item1, item2;
     std::cin &gt;&gt; item1 &gt;&gt; item2;
     // <span class="docEmphItalicAlt">first check that</span> <span class="docEmphasis">item1</span> <span class="docEmphItalicAlt">and</span> <span class="docEmphasis">item2</span> <span class="docEmphItalicAlt">represent the same book</span>
     if (item1.same_isbn(item2)) {
         std::cout &lt;&lt; item1 + item2 &lt;&lt; std::endl;
         return 0; // <span class="docEmphItalicAlt">indicate success</span>
     } else {
         std::cerr &lt;&lt; "Data must refer to same ISBN"
                   &lt;&lt; std::endl;
         return -1; // <span class="docEmphItalicAlt">indicate failure</span>
     }
</pre><br>
<p class="docText"><a name="idd1e45693"></a><a name="idd1e45699"></a><a name="idd1e45704"></a><a name="idd1e45711"></a><a name="idd1e45716"></a><a name="idd1e45722"></a><a name="idd1e45728"></a><a name="idd1e45732"></a><a name="idd1e45743"></a><a name="idd1e45748"></a><a name="idd1e45754"></a><a name="idd1e45759"></a>In a less simple program that used <tt>Sales_items</tt>, the part that adds the objects might be separated from the part that manages the interaction with a user. In this case, we might rewrite the test to <tt>throw</tt> an exception instead:</p>
<pre>
     // <span class="docEmphItalicAlt">first check that data is for the same item</span>
     if (!item1.same_isbn(item2))
         throw runtime_error("Data must refer to same ISBN");
     // <span class="docEmphItalicAlt">ok, if we're still here the ISBNs are the same</span>
     std::cout &lt;&lt; item1 + item2 &lt;&lt; std::endl;
</pre><br>
<p class="docText">In this code we check whether the ISBNs differ. If so, we discontinue execution and transfer control to a handler that will know how to handle this error.</p>
<p class="docText">A <tt>throw</tt> takes an expression. In this case, that expression is an object of type <tt>runtime_error</tt>. The <tt>runtime_error</tt> type is one of the standard library exception types and is defined in the <tt>stdexcept</tt> header. We'll have more to say about these types shortly. We create a <tt>runtime_error</tt> by giving it a <tt>string</tt>, which provides additional information about the kind of problem that occurred.</p>

<a name="ch06lev2sec14"></a>
<h4 class="docSection2Title">6.13.2. The <tt>try</tt> Block</h4>
<p class="docText">The general form of a <tt>try</tt> block is</p>
<pre>
     try {
         <span class="docEmphasis">program-statements</span>
     } catch <span class="docEmphasis">(exception-specifier)</span> {
         <span class="docEmphasis">handler-statements</span>
     } catch <span class="docEmphasis">(exception-specifier)</span> {
         <span class="docEmphasis">handler-statements</span>
     } //...
</pre><BR>
<p class="docText">A <tt>TRy</tt> block begins with the keyword <tt>try</tt> followed by a block enclosed in braces. Following the <tt>TRy</tt> block is a list of one or more catch clauses. A catch clause consists of three parts: the keyword <tt>catch</tt>, the declaration of a single type or single object within parentheses (referred to as an <b><a name="ch06term13"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_13">exception specifier</a></b>), and a block, which as usual must be enclosed in curly braces. If the catch clause is selected to handle an exception, the associated block is executed. Once the catch clause finishes, execution continues with the statement immediately following the last catch clause.</p>
<p class="docText">The <span class="docEmphasis">program-statements</span> inside the <tt>TRy</tt> constitute the normal logic of the program. They can contain any C++ statement, including declarations. Like any block, a <tt>TRy</tt> block introduces a local scope, and variables declared within a <tt>try</tt> block cannot be referred to outside the <tt>try</tt>, including within the catch clauses.</p>
<a name="ch06lev3sec3"></a>
<h5 class="docSection3Title">Writing a Handler</h5>
<p class="docText">In the preceeding example we used a <tt>tHRow</tt> to avoid adding two <tt>Sales_items</tt> that represented different books. We imagined that the part of the program that added to <tt>Sales_items</tt> was separate from the part that communicated with the <a name="idd1e45896"></a><a name="idd1e45904"></a><a name="idd1e45912"></a>user. The part that interacts with the user might contain code something like the following to handle the exception that was thrown:</p>
<pre>
     while (cin &gt;&gt; item1 &gt;&gt; item2) {
         try {
             // <span class="docEmphItalicAlt">execute code that will add the two</span> <span class="docEmphasis">Sales_items</span>
             // <span class="docEmphItalicAlt">if the addition fails, the code</span> <span class="docEmphasis">throw</span><span class="docEmphItalicAlt">s a</span> <span class="docEmphasis">runtime_error</span> <span class="docEmphItalicAlt">exception</span>
         } catch (runtime_error err) {
             // <span class="docEmphItalicAlt">remind the user that ISBN must match and prompt for another pair</span>
             cout &lt;&lt; err.what()
                  &lt;&lt; "\nTry Again? Enter y or n" &lt;&lt; endl;
             char c;
             cin &gt;&gt; c;
             if (cin &amp;&amp; c == 'n')
                 break;     // <span class="docEmphItalicAlt">break out of the</span> <span class="docEmphasis">while</span> <span class="docEmphItalicAlt">loop</span>
         }
     }
</pre><BR>
<p class="docText">Following the <tt>TRy</tt> keyword is a block. That block would invoke the part of the program that processes <tt>Sales_item</tt> objects. That part might <tt>throw</tt> an exception of type <tt>runtime_error</tt>.</p>
<p class="docText">This <tt>try</tt> block has a single <tt>catch</tt> clause, which handles exceptions of type <tt>runtime_error</tt>. The statements in the block following the <tt>catch</tt> define the actions that will be executed if code inside the <tt>TRy</tt> block throws a <tt>runtime_error</tt>. Our <tt>catch</tt> handles the error by printing a message and asking the user to indicate whether to continue. If the user enters an '<tt>n</tt>', then we break out of the <tt>while</tt>. Otherwise the loop continues by reading two new <tt>Sales_items</tt>.</P>
<p class="docText">The prompt to the user prints the return from <tt>err.what()</tt>. We know that <tt>err</tt> has type <tt>runtime_error</tt>, so we can infer that <tt>what</tt> is a member function (<a class="docLink" href="ch01lev1sec5.html#ch01lev2sec10">Section 1.5.2</a>, p. <a class="docLink" href="ch01lev1sec5.html#ch01lev2sec10">24</a>) of the <tt>runtime_error</tt> class. Each of the library exception classes defines a member function named <tt>what</tt>. This function takes no arguments and returns a C-style character string. In the case of <tt>runtime_error</tt>, the C-style string that <tt>what</tt> returns is a copy of the <tt>string</tt> that was used to initialize the <tt>runtime_error</tt>. If the code described in the previous section threw an exception, then the output printed by this <tt>catch</tt> would be</p>
<pre>
     <span class="docEmphStrong">Data must refer to same ISBN</span>
     <span class="docEmphStrong">Try Again? Enter y or n</span>
</pre><br>

<a name="ch06lev3sec4"></a>
<h5 class="docSection3Title">Functions Are Exited during the Search for a Handler</h5>
<p class="docText">In complex systems the execution path of a program may pass through multiple <tt>TRy</tt> blocks before encountering code that actually throws an exception. For example, a <tt>try</tt> block might call a function that contains a <tt>try</tt>, that calls another function with its own <tt>TRy</tt>, and so on.</p>
<p class="docText">The search for a handler reverses the call chain. When an exception is thrown, the function that threw the exception is searched first. If no matching <tt>catch</tt> is found, the function terminates, and the function that called the one that threw is searched for a matching <tt>catch</tt>. If no handler is found, then that function also <a name="idd1e46090"></a><a name="idd1e46094"></a><a name="idd1e46098"></a><a name="idd1e46102"></a><a name="idd1e46108"></a><a name="idd1e46115"></a><a name="idd1e46120"></a><a name="idd1e46126"></a><a name="idd1e46132"></a><a name="idd1e46138"></a><a name="idd1e46144"></a><a name="idd1e46148"></a><a name="idd1e46152"></a><a name="idd1e46156"></a><a name="idd1e46163"></a><a name="idd1e46169"></a><a name="idd1e46174"></a><a name="idd1e46179"></a><a name="idd1e46184"></a><a name="idd1e46188"></a><a name="idd1e46193"></a><a name="idd1e46197"></a><a name="idd1e46201"></a><a name="idd1e46207"></a><a name="idd1e46211"></a>exits and the function that called it is searched; and so on back up the execution path until a catch of an appropriate type is found.</p>
<p class="docText">If no catch clause capable of handling the exception exists, program execution is transferred to a library function named <B><a name="ch06term24"></a><a class="docLink" href="ch06lev1sec16.html#gloss06_24"><span class="docEmphStrong"><tt>terminate</tt></span></a></b>, which is defined in the <tt>exception</tt> header. The behavior of that function is system dependent, but it usually aborts the program.</p>
<p class="docText">Exceptions that occur in programs that define no <tt>TRy</tt> blocks are handled in the same manner: After all, if there are no <tt>try</tt> blocks, there can be no handlers for any exception that might be thrown. If an exception occurs, then <tt>terminate</tt> is called and the program (ordinarily) is aborted.</p>
<a name="ch06sb11"></a><p><table cellspacing="0" width="90%" border="1" cellpadding="5"><tr><td>
<h2 class="docSidebarTitle">Exercises Section 6.13.2</h2>
<blockquote>
<p><table border="0" cellspacing="16" cellpadding="0"><tr valign="top"><td align="right" class="docText" width="50"><a name="ch06qa10q1"></a><b>Exercise 6.23:</b></td><td><p class="docText">The <tt>bitset</tt> operation <tt>to_ulong</tt> tHRows an <tt>overflow_error</tt> exception if the <tt>bitset</tt> is larger than the size of an <tt>unsigned long</tt>. Write a program that generates this exception.</P>
</td></TR><tr valign="top"><td align="right" class="docText" width="50"><a name="ch06qa10q2"></a><B>Exercise 6.24:</b></TD><td><p class="docText">Revise your program to catch this exception and print a message.</p>
</td></tr></table></p>
</blockquote>
</TD></tr></table></P><BR>


<a name="ch06lev2sec15"></a>
<h4 class="docSection2Title">6.13.3. Standard Exceptions</h4>
<p class="docText">The C++ library defines a set of classes that it uses to report problems encountered in the functions in the standard library. These standard exception classes are also intended to be used in the programs we write. Library exception classes are defined in four headers:</p>
<div style="font-weight:bold"><ol class="docList" type="1"><LI><div style="font-weight:normal"><p class="docList">The <tt>exception</tt> header defines the most general kind of exception class named <tt>exception</tt>. It communicates only that an exception occurs but provides no additional information.</P></div></li><li><div style="font-weight:normal"><p class="docList">The <tt>stdexcept</tt> header defines several general purpose exception classes. These types are listed in <a class="docLink" href="#ch06table01">Table 6.1</a> on the following page.</p><a name="ch06table01"></a><p><table cellspacing="0" class="allBorders" border="1" RULES="none" cellpadding="5"><caption><H5 class="docTableTitle">Table 6.1. Standard Exception Classes Defined in <tt>&lt;stdexcept&gt;</tt></h5></caption><colgroup><col width="200"><col width="300"></colgroup><thead></thead><tr><TD class="docTableCell" align="left" valign="top"><p class="docText"><tt>exception</tt></p></td><TD class="docTableCell" align="left" valign="top"><p class="docText">The most general kind of problem.</p></TD></tr><tr><td class="docTableCell" align="left" valign="top"><p class="docText"><tt>runtime_error</tt></p></td><td class="docTableCell" align="left" valign="top"><p class="docText">Problem that can be detected only at run time.</p></td></tr><tr><td class="docTableCell" align="left" valign="top"><p class="docText"><tt>range_error</tt></p></td><TD class="docTableCell" align="left" valign="top"><p class="docText">Run-time error: result generated outside the range of values that are meaningful.</P></td></TR><tr><td class="docTableCell" align="left" valign="top"><p class="docText"><tt>overflow_error</tt></P></TD><td class="docTableCell" align="left" valign="top"><p class="docText">Run-time error: computation that overflowed.</p></td></tr><tr><TD class="docTableCell" align="left" valign="top"><p class="docText"><tt>underflow_error</tt></p></TD><TD class="docTableCell" align="left" valign="top"><p class="docText">Run-time error: computation that underflowed.</p></td></tr><TR><TD class="docTableCell" align="left" valign="top"><p class="docText"><tt>logic_error</tt></p></td><td class="docTableCell" align="left" valign="top"><p class="docText">Problem that could be detected before run time.</p></TD></tr><tr><TD class="docTableCell" align="left" valign="top"><p class="docText"><tt>domain_error</tt></p></td><TD class="docTableCell" align="left" valign="top"><p class="docText">Logic error: argument for which no result exists.</p></TD></tr><tr><td class="docTableCell" align="left" valign="top"><p class="docText"><tt>invalid_argument</tt></p></td><td class="docTableCell" align="left" valign="top"><p class="docText">Logic error: inappropriate argument.</p></td></tr><tr><td class="docTableCell" align="left" valign="top"><p class="docText"><tt>length_error</tt></p></td><TD class="docTableCell" align="left" valign="top"><p class="docText">Logic error: attempt to create an object larger than the maximum size for that type.</P></td></TR><tr><td class="docTableCell" align="left" valign="top"><p class="docText"><tt>out_of_range</tt></P></TD><td class="docTableCell" align="left" valign="top"><p class="docText">Logic error: used a value outside the valid range.</p></td></tr></table></p><BR></div></li><LI><div style="font-weight:normal"><p class="docList">The <tt>new</tt> header defines the <tt>bad_alloc</tt> exception type, which is the exception thrown by <tt>new</tt> (<a class="docLink" href="ch05lev1sec11.html#ch05lev1sec11">Section 5.11</a>, p. <a class="docLink" href="ch05lev1sec11.html#ch05lev1sec11">174</a>) if it cannot allocate memory.</P></div></li><li><div style="font-weight:normal"><p class="docList">The <tt>type_info</tt> header defines the <tt>bad_cast</tt> exception type, which we will discuss in <a class="docLink" href="ch18lev1sec2.html#ch18lev1sec2">Section 18.2</a> (p. <a class="docLink" href="ch18lev1sec2.html#ch18lev1sec2">772</a>).</p></div></LI></ol></div>
<a name="ch06lev3sec5"></a>
<H5 class="docSection3Title">Standard Library Exception Classes</h5>
<p class="docText">The library exception classes have only a few operations. We can create, copy, and assign objects of any of the exception types. The <tt>exception, bad_alloc</tt>, and <tt>bad_cast</tt> types define only a default constructor (<a class="docLink" href="ch02lev1sec3.html#ch02lev2sec13">Section 2.3.4</a>, p. <a class="docLink" href="ch02lev1sec3.html#ch02lev2sec13">50</a>); it is not possible to provide an initializer for objects of these types. The other exception types define only a single constructor that takes a <tt>string</tt> initializer. When we <a name="idd1e46526"></a><a name="idd1e46531"></a><a name="idd1e46534"></a><a name="idd1e46540"></a><a name="idd1e46548"></a>define any of these other exception types, we must supply a <tt>string</tt> argument. That <tt>string</tt> initializer is used to provide additional information about the error that occurred.</p>
<p class="docText">The exception types define only a single operation named <tt>what</tt>. That function takes no arguments and returns a <tt>const char*</tt>. The pointer it returns points to a C-style character string (<a class="docLink" href="ch04lev1sec3.html#ch04lev1sec3">Section 4.3</a>, p. <a class="docLink" href="ch04lev1sec3.html#ch04lev1sec3">130</a>). The purpose of this C-style character string is to provide some sort of textual description of the exception thrown.</p>
<p class="docText">The contents of the C-style character array to which <tt>what</tt> returns a pointer depends on the type of the exception object. For the types that take a <tt>string</tt> initializer, the <tt>what</tt> function returns that <tt>string</tt> as a C-style character array. For the other types, the value returned varies by compiler.</p>



<a href="21001535.html"><img src="images/pixel.gif" alt="" width="1" height="1" border="0"></a><UL></ul></td></TR></table>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td><div STYLE="MARGIN-LEFT: 0.15in;"><a href="toc.html"><img src="images/teamlib.gif" width="62" height="15" border="0" align="absmiddle"  alt="Team LiB"></a></div></td>
<td align="right"><div STYLE="MARGIN-LEFT: 0.15in;">
<a href=ch06lev1sec12.html><img src="images/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
<a href=ch06lev1sec14.html><img src="images/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</div></td></tr></table>
</body></html>