<html><head>
<META http-equiv="Content-Type" content="text/html">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="6.6 Error-Checking Strategies"-->
<link rel="STYLESHEET" type="text/css" href="FILES/style.css">
<link rel="STYLESHEET" type="text/css" href="FILES/docsafari.css">
<style type="text/css">	.tt1    {font-size: 10pt;}</style>
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<td class="tt1"><a href="NFO/lib.html">[ Team LiB ]</a></td><td valign="top" class="tt1" align="right">
	<a href="0596001886_pythonian-chp-6-sect-5.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
	<a href="0596001886_pythonian-chp-7.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</td></table>
<br>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td valign="top"><A NAME="pythonian-CHP-6-SECT-6"></A>
<H3 class="docSection1Title">6.6 Error-Checking Strategies</H3>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4654"></A> <A NAME="pythonian-CHP-6-ITERM-4655"></A>Most programming languages that
support exceptions are geared to raise exceptions only in very rare
cases. Python's emphasis is different. In Python,
exceptions are considered appropriate whenever they make a program
simpler and more robust. A common idiom in other languages, sometimes
known as "look before you leap"
(LBYL), is to check in advance, before attempting an operation, for
all circumstances that might make the operation invalid. This is not
ideal, for several reasons:<A NAME="pythonian-CHP-6-ITERM-4656"></A> <A NAME="pythonian-CHP-6-ITERM-4657"></A> <A NAME="pythonian-CHP-6-ITERM-4658"></A>
<A NAME="pythonian-CHP-6-ITERM-4659"></A></P>

<UL>
<LI><P class="docList">The checks may diminish the readability and clarity of the common,
mainstream cases where everything is okay.</P></LI>
<LI><P class="docList">The work needed for checking may duplicate a substantial part of the
work done in the operation itself.</P></LI>
<LI><P class="docList">The programmer might easily err by omitting some needed check.</P></LI>
<LI><P class="docList">The situation might change between the moment the checks are
performed and the moment the operation is attempted.</P></LI>
</UL>
<P class="docText">The preferred idiom in Python is generally to attempt the operation
in a <TT>try</TT> clause and handle the exceptions that may
result in <TT>except</TT> clauses. This idiom is known as
"it's easier to ask forgiveness
than permission" (EAFP), a motto widely credited to
Admiral Grace Murray Hopper, co-inventor of COBOL, and shares none of
the defects of "look before you
leap." Here is a function written using the LBYL
idiom:</P>

<PRE>def safe_divide_1(x, y):
    if y=  =0:
        print "Divide-by-0 attempt detected"
        return None
    else:
        return x/y</PRE>

<P class="docText">With LBYL, the checks come first, and the mainstream case is somewhat
hidden at the end of the function.</P>

<P class="docText">Here is the equivalent function written using the EAFP idiom:</P>

<PRE>def safe_divide_2(x, y):
    try:
        return x/y
    except ZeroDivisionError:  
        print "Divide-by-0 attempt detected"
        return None</PRE>

<P class="docText">With EAFP, the mainstream case is up front in a
<TT>try</TT> clause, and the anomalies are handled in an
<TT>except</TT> clause.</P>

<P class="docText">EAFP is most often the preferable error-handling strategy, but it is
not a panacea. In particular, you must be careful not to cast too
wide a net, catching errors that you did not expect and therefore did
not mean to catch. The following is a typical case of such a risk
(built-in function <TT>getattr</TT> is covered in <A class="docLink" HREF="0596001886_pythonian-chp-8.html#pythonian-CHP-8">Chapter 8</A>):</P>

<PRE>def trycalling(obj, attrib, default, *args, **kwds):
    try: return getattr(obj, attrib)(*args, **kwds)
    except AttributeError: return default</PRE>

<P class="docText">The intention of function <TT>trycalling</TT> is to try
calling a method named <TT>attrib</TT> on object
<TT>obj</TT>, but to return <TT>default</TT> if
<TT>obj</TT> has no method thus named. However, the
function as coded does not do just that. It also hides any error case
where <TT>AttributeError</TT> is raised inside the
implementation of the sought-after method, silently returning
<TT>default</TT> in those cases. This may hide bugs in
other code. To do exactly what is intended, the function must take a
little bit more care:</P>

<PRE>def trycalling(obj, attrib, default, *args, **kwds):
    try: method = getattr(obj, attrib)
    except AttributeError: return default
    else: return method(*args, **kwds)</PRE>

<P class="docText">This implementation of <TT>trycalling</TT> separates the
<TT>getattr</TT> call, placed in the <TT>try</TT>
clause and therefore watched over by the handler in the
<TT>except</TT> clause, from the call of the method, placed
in the <TT>else</TT> clause and therefore free to propagate
any exceptions it may need to. Using EAFP in the most effective way
involves frequent use of the <TT>else</TT> clause on
<TT>try</TT>/<TT>except</TT> statements.</P>

<A NAME="pythonian-CHP-6-SECT-6.1"></A>
<H4 class="docSection2Title">6.6.1 Handling Errors in Large Programs</H4>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4660"></A>
<A NAME="pythonian-CHP-6-ITERM-4661"></A>In large programs, it is especially easy
to err by making your
<TT>try</TT>/<TT>except</TT> statements too wide,
particularly once you have convinced yourself of the power of EAFP as
a general error-checking strategy. A
<TT>try</TT>/<TT>except</TT> is too wide when it
catches too many different errors or an error that can occur in too
many different places. The latter is a problem if you need to
distinguish exactly what happened and where, and the information in
the traceback is not sufficient to pinpoint such details (or you
discard some or all of the information in the traceback object). For
effective error handling, you have to keep a clear distinction
between errors and anomalies that you expect (and thus know exactly
how to handle), and unexpected errors and anomalies, which indicate a
bug somewhere in your program.</P>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4662"></A>Some errors and anomalies are
not really erroneous, and perhaps not even all that anomalous: they
are just special cases, perhaps rare but nevertheless quite expected,
which you choose to handle via EAFP rather than via LBYL to avoid
LBYL's many intrinsic defects. In such cases, you
should just handle the anomaly, in most cases without even logging or
reporting it. Be very careful, under these circumstances, to keep the
relevant <TT>try</TT>/<TT>except</TT> constructs
as narrow as feasible. Use a small <TT>try</TT> clause that
doesn't call too many other functions, and very
specific exception-class lists in the <TT>except</TT>
clauses.</P>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4663"></A>Errors and anomalies that depend on user
input or other external conditions not under your control are always
expected to some extent, precisely because you have no control on
their underlying causes. In such cases, you should concentrate your
effort on handling the anomaly gracefully, normally reporting and
logging its exact nature and details, and generally keep your program
running with undamaged internal and persistent states. The width of
<TT>try</TT>/<TT>except</TT> clauses under such
circumstances should also be reasonably narrow, although this is not
quite as crucial as when you use EAFP to structure your handling of
not-really-erroneous special cases.</P>

<P class="docText">Lastly, entirely unexpected errors and anomalies indicate bugs in
your program's design or coding. In most cases, the
best strategy regarding such errors is to avoid
<TT>try</TT>/<TT>except</TT> and just let the
program terminate with error and traceback messages. (You might even
want to log such information and/or display it more suitably with an
application-specific hook in <TT>sys.excepthook</TT>, as
we'll discuss shortly.) If your program must keep
running at all costs, even under such circumstances,
<TT>try</TT>/<TT>except</TT> statements that are
quite wide may be appropriate, with the <TT>try</TT> clause
guarding function calls that exercise vast swaths of program
functionality and broad <TT>except</TT> clauses.</P>

<P class="docText">In the case of a long-running program, make sure all details of the
anomaly or error are logged to some persistent place for later study
(and that some indication gets displayed, too, so that you know such
later study is necessary). The key is making sure that the
program's persistent state can be reverted to some
undamaged, internally consistent point. The techniques that enable
long-running programs to survive some of their own bugs are known as
checkpointing and transactional behavior, but they are not covered
further in this book.</P>


<A NAME="pythonian-CHP-6-SECT-6.2"></A>
<H4 class="docSection2Title">6.6.2 Logging Errors</H4>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4664"></A>When Python propagates an exception all
the way to the top of the stack without finding an applicable
handler, the interpreter normally prints an error traceback to the
standard error stream of the process (<TT>sys.stderr</TT>)
before terminating the program. You can rebind
<TT>sys.stderr</TT> to any file-like object usable for
output in order to divert this information to a destination more
suitable for your purposes.<A NAME="pythonian-CHP-6-ITERM-4665"></A></P>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4666"></A> <A NAME="pythonian-CHP-6-ITERM-4667"></A>
<A NAME="pythonian-CHP-6-ITERM-4668"></A> <A NAME="pythonian-CHP-6-ITERM-4669"></A>When you want to change the amount
and kind of information output on such occasions, rebinding
<TT>sys.stderr</TT> is not sufficient. In such cases, you
can assign your own function to <TT>sys.excepthook</TT>,
and Python will call it before terminating the program due to an
unhandled exception. In your exception-reporting function, you can
output whatever information you think will later help you diagnose
and debug the problem to whatever destinations you please. For
example, you might use module <TT>traceback</TT> (covered
in <A class="docLink" HREF="0596001886_pythonian-chp-17.html#pythonian-CHP-17">Chapter 17</A>) to help you format stack traces.
When your exception-reporting function terminates, so does your
program.</P>


<A NAME="pythonian-CHP-6-SECT-6.3"></A>
<H4 class="docSection2Title">6.6.3 The assert Statement</H4>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4670"></A> <A NAME="pythonian-CHP-6-ITERM-4671"></A>
<A NAME="pythonian-CHP-6-ITERM-4672"></A>
<A NAME="pythonian-CHP-6-ITERM-4673"></A>
<A NAME="pythonian-CHP-6-ITERM-4674"></A>The
<TT>assert</TT> statement allows you to introduce debugging
code into a program. <TT>assert</TT> is a simple statement
with the following syntax:</P>

<PRE>assert <TT><I>condition</I></TT>[,<TT><I>expression</I></TT>]</PRE>

<P class="docText">When you run Python with the optimize flag (<TT>-O</TT>, as
covered in <A class="docLink" HREF="0596001886_pythonian-chp-3.html#pythonian-CHP-3">Chapter 3</A>), <TT>assert</TT>
is a null operation: the compiler generates no code. Otherwise,
<TT>assert</TT> evaluates
<TT><I>condition</I></TT>. If
<TT><I>condition</I></TT> is satisfied,
<TT>assert</TT> does nothing. If
<TT><I>condition</I></TT> is not satisfied,
<TT>assert</TT> instantiates
<TT>AssertionError</TT> with
<TT><I>expression</I></TT> as the argument (or without
arguments, if there is no <TT><I>expression</I></TT>) and
raises the resulting instance.</P>

<P class="docText"><TT>assert</TT> statements are an effective way to document
your program. When you want to state that a significant condition
<TT><I>C</I></TT> is known to hold at a certain point in a
program's execution, <TT>assert</TT>
<TT><I>C</I></TT> is better than a comment that just
states <TT><I>C</I></TT>. The advantage of
<TT>assert</TT> is that when the condition does not in fact
hold, <TT>assert</TT> alerts you to the problem by raising
<TT>AssertionError</TT>.<A NAME="pythonian-CHP-6-ITERM-4675"></A></P>


<A NAME="pythonian-CHP-6-SECT-6.4"></A>
<H4 class="docSection2Title">6.6.4 The _ _debug_ _ Built-in Variable</H4>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4676"></A>
<A NAME="pythonian-CHP-6-ITERM-4677"></A>
<A NAME="pythonian-CHP-6-ITERM-4678"></A>When
you run Python without option <TT>-O</TT>, the <TT>_
_debug_ _</TT> built-in variable is <TT>True</TT>.
When you run Python with option <TT>-O</TT>, <TT>_
_debug_ _</TT> is <TT>False</TT>. Also, with option
<TT>-O</TT>, the compiler generates no code for an
<TT>if</TT> statement whose condition is <TT>_ _debug_
_</TT>.</P>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4679"></A>To exploit this
optimization, surround the definitions of functions that you call
only in <TT>assert</TT> statements with
<TT>if</TT> <TT>_ _debug_ _</TT>. This technique
makes compiled code smaller and faster when Python is run with
<TT>-O</TT>, and enhances program clarity by showing that
the functions exist only to perform sanity checks.<A NAME="pythonian-CHP-6-ITERM-4680"></A> <A NAME="pythonian-CHP-6-ITERM-4681"></A></P>



<ul></ul>
</td>
</tr>
</table>
<td></td>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<td class="tt1"><a href="NFO/lib.html">[ Team LiB ]</a></td><td valign="top" class="tt1" align="right">
          <a href="0596001886_pythonian-chp-6-sect-5.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
          <a href="0596001886_pythonian-chp-7.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</td></table>
</body></html>
