<html><head>
<META http-equiv="Content-Type" content="text/html">
<!--SafClassName="docSection1Title"--><!--SafTocEntry="6.1 The try Statement"-->
<link rel="STYLESHEET" type="text/css" href="FILES/style.css">
<link rel="STYLESHEET" type="text/css" href="FILES/docsafari.css">
<style type="text/css">	.tt1    {font-size: 10pt;}</style>
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<td class="tt1"><a href="NFO/lib.html">[ Team LiB ]</a></td><td valign="top" class="tt1" align="right">
	<a href="0596001886_pythonian-chp-6.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
	<a href="0596001886_pythonian-chp-6-sect-2.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</td></table>
<br>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td valign="top"><A NAME="pythonian-CHP-6-SECT-1"></A>
<H3 class="docSection1Title">6.1 The try Statement</H3>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4555"></A>
<A NAME="pythonian-CHP-6-ITERM-4556"></A>The <TT>try</TT> statement
provides Python's exception-handling mechanism. It
is a compound statement that can take one of two different forms:</P>

<UL>
<LI><P class="docList">A <TT>try</TT> clause followed by one or more
<TT>except</TT> clauses</P></LI>
<LI><P class="docList">A <TT>try</TT> clause followed by exactly one
<TT>finally</TT> clause</P></LI>
</UL>
<A NAME="pythonian-CHP-6-SECT-1.1"></A>
<H4 class="docSection2Title">6.1.1 try/except</H4>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4557"></A>
<A NAME="pythonian-CHP-6-ITERM-4558"></A>Here's the syntax for the
<TT>try</TT>/<TT>except</TT> form of the
<TT>try</TT> statement:</P>

<PRE>try:
    <TT><I>statement(s)</I></TT>
except [<TT><I>expression</I></TT> [, <TT><I>target</I></TT>]]:
    <TT><I>statement(s)</I></TT>
[else:
    <TT><I>statement(s)</I></TT>]</PRE>

<P class="docText">This form of the <TT>try</TT> statement has one or more
<TT>except</TT> clauses, as well as an optional
<TT>else</TT> clause.</P>

<P class="docText">The body of each <TT>except</TT> clause is known as an
<I>exception</I> <I>handler</I>. The code
executes if the <TT><I>expression</I></TT> in the
<TT>except</TT> clause matches an exception object that
propagates from the <TT>try</TT> clause.
<TT><I>expression</I></TT> is an optional class or tuple
of classes that matches any exception object of one of the listed
classes or any of their subclasses. The optional
<TT><I>target</I></TT> is an identifier that names a
variable that Python binds to the exception object just before the
exception handler executes. A handler can also obtain the current
exception object by calling the <TT>exc_info</TT> function
of module <TT>sys</TT> (covered in <A class="docLink" HREF="0596001886_pythonian-chp-8.html#pythonian-CHP-8">Chapter 8</A>).</P>

<P class="docText">Here is an example of the
<TT>try</TT>/<TT>except</TT> form of the
<TT>try</TT> statement:</P>

<PRE>try: 1/0
except ZeroDivisionError: print "caught divide-by-0 attempt"</PRE>

<P class="docText">If a <TT>try</TT> statement has several
<TT>except</TT> clauses, the exception propagation
mechanism tests the <TT>except</TT> clauses in order: the
first <TT>except</TT> clause whose expression matches the
exception object is used as the handler. Thus, you must always list
handlers for specific cases before you list handlers for more general
cases. If you list a general case first, the more specific
<TT>except</TT> clauses that follow will never enter the
picture.</P>

<P class="docText">The last <TT>except</TT> clause may lack an expression.
This clause handles any exception that reaches it during propagation.
Such unconditional handling is a rare need, but it does occur,
generally in wrapper functions that must perform some extra task
before reraising an exception, as we'll discuss
later in the chapter.</P>

<P class="docText">Note that exception propagation terminates when it finds a handler
whose expression matches the exception object. Thus, if a
<TT>try</TT> statement is nested in the
<TT>try</TT> clause of another <TT>try</TT>
statement, a handler established by the inner <TT>try</TT>
is reached first during propagation, and therefore is the one that
handles the exception, if it matches the expression. For example:</P>

<PRE>try:
    try: 1/0
    except: print "caught an exception"
except ZeroDivisionError:
    print "caught divide-by-0 attempt"
# prints: caught an exception</PRE>

<P class="docText">In this case, it does not matter that the handler established by
clause <TT>except</TT>
<TT>ZeroDivisionError</TT>: in the outer
<TT>try</TT> clause is more specific and appropriate than
the catch-all <TT>except</TT>: in the inner
<TT>try</TT> clause. The outer <TT>try</TT> does
not even enter into the picture because the exception
doesn't propagate out of the inner
<TT>try</TT>.</P>

<P class="docText">The optional <TT>else</TT> clause of
<TT>try</TT>/<TT>except</TT> executes only if the
<TT>try</TT> clause terminates normally. In other words, it
does not execute if an exception propagates from the
<TT>try</TT> clause or if the <TT>try</TT> clause
exits with a <TT>break</TT>, <TT>continue</TT>,
or <TT>return</TT> statement. The handlers established by
<TT>try</TT>/<TT>except</TT> cover only the
<TT>try</TT> clause, not the <TT>else</TT>
clause. The <TT>else</TT> clause is useful to avoid
accidentally handling unexpected exceptions. For example:</P>

<A NAME="pythonian-CHP-6-ITERM-4559"></A><A NAME="pythonian-CHP-6-ITERM-4560"></A><PRE>print repr(value), "is ",
try:
    value + 0
except TypeError:
    # not a number, maybe a string, Unicode, UserString...?
    try:
        value + ''
    except TypeError:
        print "neither a number nor a string"
    else:
        print "a string or string-like value"
else:
    print "a number of some kind"</PRE>


<A NAME="pythonian-CHP-6-SECT-1.2"></A>
<H4 class="docSection2Title">6.1.2 try/finally</H4>

<P class="docText"><A NAME="pythonian-CHP-6-ITERM-4561"></A>
<A NAME="pythonian-CHP-6-ITERM-4562"></A>Here's the syntax for the
<TT>try</TT>/<TT>finally</TT> form of the
<TT>try</TT> statement:</P>

<PRE>try:
    <TT><I>statement(s)</I></TT>
finally:
    <TT><I>statement(s)</I></TT></PRE>

<P class="docText">This form has exactly one <TT>finally</TT> clause, and it
cannot have an <TT>else</TT> clause.</P>

<P class="docText">The <TT>finally</TT> clause establishes what is known as a
<I>clean-up</I> <I>handler</I>. The code
always executes after the <TT>try</TT> clause terminates in
any way. When an exception propagates from the <TT>try</TT>
clause, the <TT>try</TT> clause terminates, the clean-up
handler executes, and the exception keeps propagating. When no
exception occurs, the clean-up handler executes anyway, whether the
<TT>try</TT> clause reaches its end or exits by executing a
<TT>break</TT>, <TT>continue</TT>, or
<TT>return</TT> statement.</P>

<P class="docText">Clean-up handlers established with <TT>try/finally</TT>
offer a robust and explicit way to specify finalization code that
must always execute, no matter what, to ensure consistency of program
state and/or external entities (e.g., files, databases, network
connections). Here is an example of the
<TT>try</TT>/<TT>finally</TT> form of the
<TT>try</TT> statement:</P>

<PRE>f = open(someFile, "w")
try:
    do_something_with_file(f)
finally:
    f.close(  )</PRE>

<P class="docText">Note that the <TT>try</TT>/<TT>finally</TT> form
is distinct from the <TT>try</TT>/<TT>except</TT>
form: a <TT>try</TT> statement cannot have both
<TT>except</TT> and <TT>finally</TT> clauses, as
execution order might be ambiguous. If you need both exception
handlers and a clean-up handler, nest a <TT>try</TT>
statement in the <TT>try</TT> clause of another
<TT>try</TT> statement to define execution order explicitly
and unambiguously.</P>

<P class="docText">A <TT>finally</TT> clause cannot directly contain a
<TT>continue</TT> statement, but it may contain a
<TT>break</TT> or <TT>return</TT> statement. Such
usage, however, makes your program less clear, as exception
propagation stops when such a <TT>break</TT> or
<TT>return</TT> executes. Most programmers would not
normally expect propagation to be stopped in a
<TT>finally</TT> clause, so this usage may confuse people
who are reading your code.<A NAME="pythonian-CHP-6-ITERM-4563"></A> <A NAME="pythonian-CHP-6-ITERM-4564"></A></P>



<ul></ul>
</td>
</tr>
</table>
<td></td>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<td class="tt1"><a href="NFO/lib.html">[ Team LiB ]</a></td><td valign="top" class="tt1" align="right">
          <a href="0596001886_pythonian-chp-6.html"><img src="FILES/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
          <a href="0596001886_pythonian-chp-6-sect-2.html"><img src="FILES/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a>
</td></table>
</body></html>
